import { createTheme } from "@fluentui/react";

export const UeliColorThemes = {
    UeliDark: createTheme({
        palette: {
            themePrimary: "#55efc4",
            themeLighterAlt: "#030a08",
            themeLighter: "#0e261f",
            themeLight: "#1a483b",
            themeTertiary: "#349076",
            themeSecondary: "#4cd3ad",
            themeDarkAlt: "#66f1ca",
            themeDark: "#7df3d2",
            themeDarker: "#9ef6dd",
            neutralLighterAlt: "#1d262d",
            neutralLighter: "#1d252c",
            neutralLight: "#1b242a",
            neutralQuaternaryAlt: "#1a2127",
            neutralQuaternary: "#182025",
            neutralTertiaryAlt: "#171f24",
            neutralTertiary: "#c8c8c8",
            neutralSecondary: "#d0d0d0",
            neutralPrimaryAlt: "#dadada",
            neutralPrimary: "#ffffff",
            neutralDark: "#f4f4f4",
            black: "#f8f8f8",
            white: "#1e272e",
        },
    }),
    UeliLight: createTheme({
        palette: {
            themePrimary: "#00b894",
            themeLighterAlt: "#000706",
            themeLighter: "#001d18",
            themeLight: "#00372c",
            themeTertiary: "#006e58",
            themeSecondary: "#00a281",
            themeDarkAlt: "#13bf9c",
            themeDark: "#30c9aa",
            themeDarker: "#5fd7bf",
            neutralLighterAlt: "#d9dfe2",
            neutralLighter: "#d5dbde",
            neutralLight: "#cdd2d5",
            neutralQuaternaryAlt: "#bec4c6",
            neutralQuaternary: "#b6bbbd",
            neutralTertiaryAlt: "#afb4b6",
            neutralTertiary: "#595959",
            neutralSecondary: "#373737",
            neutralPrimaryAlt: "#2f2f2f",
            neutralPrimary: "#000000",
            neutralDark: "#151515",
            black: "#0b0b0b",
            white: "#dfe6e9",
        },
    }),
    WindowsDark: createTheme({
        palette: {
            themePrimary: "#0078d4",
            themeLighterAlt: "#eff6fc",
            themeLighter: "#deecf9",
            themeLight: "#c7e0f4",
            themeTertiary: "#71afe5",
            themeSecondary: "#2b88d8",
            themeDarkAlt: "#106ebe",
            themeDark: "#005a9e",
            themeDarker: "#004578",
            neutralLighterAlt: "#1c1a19",
            neutralLighter: "#252321",
            neutralLight: "#34322f",
            neutralQuaternaryAlt: "#3d3a37",
            neutralQuaternary: "#45423f",
            neutralTertiaryAlt: "#65615d",
            neutralTertiary: "#c8c8c8",
            neutralSecondary: "#d0d0d0",
            neutralPrimaryAlt: "#dadada",
            neutralPrimary: "#ffffff",
            neutralDark: "#f4f4f4",
            black: "#f8f8f8",
            white: "#11100f",
        },
    }),
    WindowsLight: createTheme({
        palette: {
            themePrimary: "#0078d4",
            themeLighterAlt: "#eff6fc",
            themeLighter: "#deecf9",
            themeLight: "#c7e0f4",
            themeTertiary: "#71afe5",
            themeSecondary: "#2b88d8",
            themeDarkAlt: "#106ebe",
            themeDark: "#005a9e",
            themeDarker: "#004578",
            neutralLighterAlt: "#f8f8f8",
            neutralLighter: "#f4f4f4",
            neutralLight: "#eaeaea",
            neutralQuaternaryAlt: "#dadada",
            neutralQuaternary: "#d0d0d0",
            neutralTertiaryAlt: "#c8c8c8",
            neutralTertiary: "#595959",
            neutralSecondary: "#373737",
            neutralPrimaryAlt: "#2f2f2f",
            neutralPrimary: "#000000",
            neutralDark: "#151515",
            black: "#0b0b0b",
            white: "#ffffff",
        },
    }),
};
