name: Build

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-22.04
        name: Build
        steps:
            - name: Checkout current commit/branch/tag
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install npm dependencies
              run: npm install
              env:
                  NODE_ENV: development

            - name: Lint files
              run: npm run lint

            - name: Typechecks
              run: npm run typecheck

            - name: Prettier check
              run: npm run prettier:check

            - name: Run tests
              run: npm run test

            - name: Build app
              run: npm run build
